dependencies:
- smartcontractkit/chainlink-brownie-contracts@1.1.1
- OpenZepplin/openzepplin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzepplin=OpenZepplin/openzepplin-contracts@3.4.0'
networks:
  default: development
  development:
    keyhash: 
    fee: 
  goerli :
    vrf_coordinator: '0x2bce784e69d2Ff36c71edcB9F88358dB0DfB55b4'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  wallets:
    from_key:${PRIVATE_KEY}